version: "1"

networks:
  gobase:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456password
      MYSQL_DATABASE: healthnet
      MYSQL_USER: anhnv
      MYSQL_PASSWORD: 123456
    ports:
      - '3309:3306'
    volumes:
      - C:\Users\anhnv\Desktop\coding\course\iam\mysql-data:/var/lib/mysql
    networks:
      - gobase

#  jaeger:
#    image: jaegertracing/all-in-one:1.46
#    restart: always
#    environment:
#      COLLECTOR_OTLP_ENABLED: true
#      COLLECTOR_ZIPKIN_HOST_PORT: :9411
#    ports:
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
#      - 16686:16686
#      - 4317:4317
#      - 4318:4318
#      - 14250:14250
#      - 14268:14268
#      - 14269:14269
#      - 9411:9411
#    networks:
#      - gobase

  api:
    image: vietanhd14cn7/gobase:latest
#    stdin_open: true
#    tty: true
    depends_on:
      - mysql
    ports:
      - 9002:9002
      - 8002:8002
    networks:
      - gobase
