FROM ubuntu:20.04

RUN     apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        tzdata \
        rsyslog \
        ntp \
        bash \
        htop \
        atop \
        vim \
        wget \
        rsync \
        mlocate \
        collectd \
        ca-certificates \
        logwatch


RUN wget "https://go.dev/dl/go1.20.5.linux-amd64.tar.gz" && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

